version: "3.3"
volumes:
  db:
    driver: local
services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    image: instadevskill-app
    container_name: instadevskill-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - laravel-network
  db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: instadevskill
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_PASSWORD: pass
      MYSQL_USER: root
    ports:
      - "3306:3306"
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    networks:
      - laravel-network
  nginx:
    image: nginx:alpine
    container_name: instadevskill-nginx
    restart: unless-stopped
    ports:
      - 5000:80
    volumes:
      - ./:/var/www
      - ./touch.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network
networks:
  laravel-network:
    driver: bridge
